server:
  port: 8080

spring:
  application:
    name: PAY
  redis:
    port: 6379
    password: 270018
    host: 123.249.2.30

ali:
  appId: ""
  uId: ""
  opAppId: ""
  privateKey: ""
  publicKey: ""
  notifyUrl: ""
  pcReturnUrl: ""
  h5ReturnUrl: ""
  signType: ""
  charSet: ""
  gateWayUrl: ""
  appCertPath: ""
  aliPayCertPath: ""
  aliPayRootCertPath: ""

wechat:
  appId: ""
  mchId: ""
  notifyUrl: ""
  serialNumber: ""
  apiKey3: ""
  privateKey: ""
